# Generated by Django 5.2.4 on 2025-07-13 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_category_maqola_maxsulot'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maqolalar', to='chat.category'),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Maxsulot',
        ),
    ]
